const Menu = [{
    id: 1,
    image: "images/Momo.jpg",
    name: "Momo",
    category: "Snacks",
    price: "Rs. 150",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 2,
    image: "images/chowmein.jpg",
    name: "Chowmein",
    category: "Snacks",
    price: "Rs. 100",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 3,
    image: "images/roll.jpg",
    name: "Katti roll",
    category: "Snacks",
    price: "Rs. 200",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 4,
    image: "images/sanwich.jpg",
    name: "Sanwich",
    category: "Snacks",
    price: "Rs. 300",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 5,
    image: "images/fries.jpg",
    name: "French fries",
    category: "Snacks",
    price: "Rs. 180",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 6,
    image: "images/cake.jpg",
    name: "Cake",
    category: "Dessert",
    price: "Rs. 200",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 7,
    image: "images/icecream.jpg",
    name: "Icecream",
    category: "Dessert",
    price: "Rs. 300",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 8,
    image: "images/sweets.jpg",
    name: "Sweets",
    category: "Dessert",
    price: "Rs. 400",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 9,
    image: "images/coke.jpg",
    name: "Cocacola",
    category: "Drinks",
    price: "Rs. 50",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 10,
    image: "images/sprite.jpg",
    name: "Sprite",
    category: "Drinks",
    price: "Rs. 50",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 11,
    image: "images/slice.jpg",
    name: "Slice",
    category: "Drinks",
    price: "Rs. 60",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
{
    id: 12,
    image: "images/lassi.jpg",
    name: "Lassi",
    category: "Drinks",
    price: "Rs. 80",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quibusdam tempore delectus nemo, maxime nostrum ducimus?",
},
]

export default Menu